version: '3.8'

services:
  backend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file: ../.env
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: 'postgres:15.5'
    ports:
      - 5433:5432
    env_file: ./.env
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      ENV: dev

networks:
  backend:

volumes:
  postgres:
