version: '3.8'

services:
  dev-db:
    image: postgres:16
    ports:
      - 5432:5432
    env_file: ../.env
    networks:
      - nestapp

  nest-app:
    build:
      context: ../
      dockerfile: ./docker/deploy/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - dev-db
    networks:
      - nestapp

networks:
  nestapp:
